INSERT INTO EOLICAS VALUES ('TACICA DE PLATA', '7.17');
INSERT INTO EOLICAS VALUES ('LOMA DEL CAPÓN', '7.24');
INSERT INTO EOLICAS VALUES ('LOMA DE AYALA', '8.83');
INSERT INTO EOLICAS VALUES ('THARSIS', '7.32');
INSERT INTO EOLICAS VALUES ('LLANOS DEL ESPINO', '8.05');
INSERT INTO EOLICAS VALUES ('EL COLMENAR II', '8.82');
