INSERT INTO MUNICIPIOS VALUES('043', '04', 'ALBOLODUY');
INSERT INTO MUNICIPIOS VALUES('295', '29', 'ALMARGEN Y TEBA');
INSERT INTO MUNICIPIOS VALUES('182', '18', 'ALBUÑUELAS');
INSERT INTO MUNICIPIOS VALUES('041', '04', 'ABLA Y LAS TRES VILLAS');
INSERT INTO MUNICIPIOS VALUES('046', '04', 'ABRUCENA Y FIÑANA');
INSERT INTO MUNICIPIOS VALUES('214', '21', 'ALOSNO');
