INSERT INTO EOLICAS VALUES ('TACICA DE PLATA', '8.51');
INSERT INTO EOLICAS VALUES ('LOMA DEL CAPÓN', '6.7');
INSERT INTO EOLICAS VALUES ('LOMA DE AYALA', '6.96');
INSERT INTO EOLICAS VALUES ('THARSIS', '7.31');
INSERT INTO EOLICAS VALUES ('LLANOS DEL ESPINO', '8.72');
INSERT INTO EOLICAS VALUES ('EL COLMENAR II', '7.73');
