use fasedos;
INSERT INTO EOLICAS VALUES ('TACICA DE PLATA', '8.77');
INSERT INTO EOLICAS VALUES ('LOMA DEL CAPÓN', '7.13');
INSERT INTO EOLICAS VALUES ('LOMA DE AYALA', '6.45');
INSERT INTO EOLICAS VALUES ('THARSIS', '8.14');
INSERT INTO EOLICAS VALUES ('LLANOS DEL ESPINO', '8.21');
INSERT INTO EOLICAS VALUES ('EL COLMENAR II', '8.99');
